FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit==1.31.1 \
    folium==0.16.0 \
    streamlit-folium==0.18.0 \
    plotly==5.19.0 \
    pandas==2.2.0 \
    requests==2.31.0 \
    python-dotenv==1.0.1

COPY dashboard/ .
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
